# yaml file for configuration
# this is conventional yaml format:
# http://www.yaml.org/start.html
# comment out rows you don't want
setup:
    # default extension to look for
    extension: ".imm"
    # the parent directory
    DDIR: "." 
    # the storage directory
    SDIR: "."
    # beam center
    xcen: 1313.39
    ycen: 1267.81
    # wait time for file listening
    wait_time: .1
    # the initial mask name
    mask_name: "/home/lhermitte/research/projects/julanal_yr/data/mask_gep6cC.hd5"
    # the values that define masked and unmasked region >=
    mask_threshold: 1
    # sample detector distance
    rdet: 3.800 # in m
    energy: 7.44137  # in keV
    wavelength: 1.6660910558136472  # in angstroms
    dpix: 20 # pixel size in um
    # first filename to load
    filename: "/home/lhermitte/research/projects/julanal_yr/data/gep6cC_4_00641-01150.imm"
    transformation: [ [1, 0],
                      [0, 1]
                    ]
# parameters for circavg computations
circavg:
    noqs: 800 #partitioning for circular average/qphi maps
# parameters for qphi avg computations
qphiavg:
    noqs: 800 #partitioning for circular average/qphi maps
    nophis: 360 #partitioning for qphimaps in phi
deltaphicorr:
    noqs: 800 #partitioning for circular average/qphi maps
    nophis: 360 #partitioning for qphimaps in phi
